name: "vim help tag name check"
on: push
jobs:
  tagname:
    name: Check tag name conflict
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: help tag check
        uses: tsuyoshicho/action-vimhelp-tagname-check@v1
