name: "vim help tag name check"
on: [push, pull_request]
jobs:
  tagname:
    name: Check tag name conflict
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: help tag check
        uses: tsuyoshicho/action-vimhelp-tagname-check@3140c342f2dde6b2402e622e580c92f30ce69a28 # v1.1.3
