name: "vim help tag name check"
on: [push, pull_request]
jobs:
  tagname:
    name: Check tag name conflict
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: help tag check
        uses: tsuyoshicho/action-vimhelp-tagname-check@v1.1.2
